# Generated by Django 5.0.2 on 2026-04-03 01:01

import django.db.models.deletion
import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Linguagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                (
                    "aliases",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Apelidos/AKA"
                    ),
                ),
                (
                    "descricao_breve",
                    models.TextField(blank=True, verbose_name="Descrição Curta"),
                ),
                (
                    "conteudo",
                    mdeditor.fields.MDTextField(verbose_name="Conteúdo Principal"),
                ),
                (
                    "referencias",
                    mdeditor.fields.MDTextField(
                        blank=True, verbose_name="Referências e Guias Práticos"
                    ),
                ),
                ("link_oficial", models.URLField(blank=True, max_length=500)),
                ("link_documentacao", models.URLField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "nivel_abstracao",
                    models.CharField(
                        choices=[
                            ("Baixo", "Baixo"),
                            ("Médio", "Médio"),
                            ("Alto", "Alto"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "modo_execucao",
                    models.CharField(
                        choices=[
                            ("Compilado", "Compilado"),
                            ("Interpretado", "Interpretado"),
                            ("Híbrida/JIT", "Híbrida/JIT"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tipagem",
                    models.CharField(
                        choices=[
                            ("Estática", "Estática"),
                            ("Dinâmica", "Dinâmica"),
                            ("Forte", "Forte"),
                            ("Fraca", "Fraca"),
                            ("untyped", "untyped"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Linguagens",
            },
        ),
        migrations.CreateModel(
            name="Paradigma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name_plural": "Paradigmas",
            },
        ),
        migrations.CreateModel(
            name="Framework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                (
                    "aliases",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Apelidos/AKA"
                    ),
                ),
                (
                    "descricao_breve",
                    models.TextField(blank=True, verbose_name="Descrição Curta"),
                ),
                (
                    "conteudo",
                    mdeditor.fields.MDTextField(verbose_name="Conteúdo Principal"),
                ),
                (
                    "referencias",
                    mdeditor.fields.MDTextField(
                        blank=True, verbose_name="Referências e Guias Práticos"
                    ),
                ),
                ("link_oficial", models.URLField(blank=True, max_length=500)),
                ("link_documentacao", models.URLField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "linguagem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frameworks",
                        to="core.linguagem",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Frameworks",
            },
        ),
        migrations.CreateModel(
            name="Biblioteca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                (
                    "aliases",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Apelidos/AKA"
                    ),
                ),
                (
                    "descricao_breve",
                    models.TextField(blank=True, verbose_name="Descrição Curta"),
                ),
                (
                    "conteudo",
                    mdeditor.fields.MDTextField(verbose_name="Conteúdo Principal"),
                ),
                (
                    "referencias",
                    mdeditor.fields.MDTextField(
                        blank=True, verbose_name="Referências e Guias Práticos"
                    ),
                ),
                ("link_oficial", models.URLField(blank=True, max_length=500)),
                ("link_documentacao", models.URLField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "linguagem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bibliotecas",
                        to="core.linguagem",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Bibliotecas",
            },
        ),
        migrations.CreateModel(
            name="BancoDeDados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                (
                    "aliases",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Apelidos/AKA"
                    ),
                ),
                (
                    "descricao_breve",
                    models.TextField(blank=True, verbose_name="Descrição Curta"),
                ),
                (
                    "conteudo",
                    mdeditor.fields.MDTextField(verbose_name="Conteúdo Principal"),
                ),
                (
                    "referencias",
                    mdeditor.fields.MDTextField(
                        blank=True, verbose_name="Referências e Guias Práticos"
                    ),
                ),
                ("link_oficial", models.URLField(blank=True, max_length=500)),
                ("link_documentacao", models.URLField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("SQL", "Relacional (SQL)"),
                            ("NoSQL", "Não-Relacional (NoSQL)"),
                            ("NewSQL", "NewSQL"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "linguagens_compativeis",
                    models.ManyToManyField(blank=True, to="core.linguagem"),
                ),
            ],
            options={
                "verbose_name": "Banco de Dados",
                "verbose_name_plural": "Bancos de Dados",
            },
        ),
        migrations.AddField(
            model_name="linguagem",
            name="paradigmas",
            field=models.ManyToManyField(
                blank=True, related_name="linguagens", to="core.paradigma"
            ),
        ),
        migrations.CreateModel(
            name="Vaga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("empresa", models.CharField(max_length=100)),
                ("link_anuncio", models.URLField(max_length=500)),
                ("data_postagem", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Interesse", "Apenas Interesse"),
                            ("Aplicado", "Currículo Enviado"),
                            ("Entrevista", "Em Fase de Entrevistas"),
                            ("Teste", "Teste Técnico em Andamento"),
                            ("Negado", "Não Selecionada"),
                            ("Aprovado", "Contratada! 🎉"),
                        ],
                        default="Interesse",
                        max_length=20,
                    ),
                ),
                (
                    "descricao_vaga",
                    mdeditor.fields.MDTextField(
                        help_text="Cole aqui a descrição completa para consulta posterior"
                    ),
                ),
                (
                    "anotacoes_pessoais",
                    mdeditor.fields.MDTextField(
                        help_text="O que você estudou ou preparou para essa vaga específica?"
                    ),
                ),
                (
                    "requisitos_bancos",
                    models.ManyToManyField(blank=True, to="core.bancodedados"),
                ),
                (
                    "requisitos_bibliotecas",
                    models.ManyToManyField(blank=True, to="core.biblioteca"),
                ),
                (
                    "requisitos_frameworks",
                    models.ManyToManyField(blank=True, to="core.framework"),
                ),
                (
                    "requisitos_linguagens",
                    models.ManyToManyField(blank=True, to="core.linguagem"),
                ),
            ],
            options={
                "verbose_name_plural": "Vagas",
            },
        ),
        migrations.CreateModel(
            name="Aplicacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_envio", models.DateField(auto_now_add=True)),
                (
                    "etapa_atual",
                    models.CharField(
                        choices=[
                            ("CV", "Envio de Currículo"),
                            ("Fit", "Fit Cultural / RH"),
                            ("Tecnico", "Teste Técnico"),
                            ("Gestor", "Entrevista com Gestor"),
                            ("Proposta", "Proposta Recebida"),
                        ],
                        default="CV",
                        max_length=20,
                    ),
                ),
                (
                    "curriculo_versao",
                    models.CharField(
                        blank=True,
                        help_text="Ex: CV_DataScience_v2.pdf",
                        max_length=100,
                    ),
                ),
                (
                    "portfolio_link",
                    models.URLField(
                        blank=True, help_text="Link para o projeto enviado"
                    ),
                ),
                (
                    "feedback_recebido",
                    mdeditor.fields.MDTextField(
                        blank=True, help_text="O que a empresa disse sobre você?"
                    ),
                ),
                (
                    "anotacoes_pos_entrevista",
                    mdeditor.fields.MDTextField(
                        blank=True, help_text="O que você achou da empresa?"
                    ),
                ),
                (
                    "vaga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aplicacoes",
                        to="core.vaga",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Aplicações",
            },
        ),
    ]
