# Generated by Django 5.0.2 on 2026-03-01 06:44

import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paradigma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Linguagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "nivel_abstracao",
                    models.CharField(
                        choices=[
                            ("Baixo", "Baixo"),
                            ("Médio", "Médio"),
                            ("Alto", "Alto"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "modo_execucao",
                    models.CharField(
                        choices=[
                            ("Compilado", "Compilado"),
                            ("Interpretado", "Interpretado"),
                            ("Híbrida/JIT", "Híbrida/JIT"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tipagem",
                    models.CharField(
                        choices=[
                            ("Estática", "Estática"),
                            ("Dinâmica", "Dinâmica"),
                            ("Forte", "Forte"),
                            ("Fraca", "Fraca"),
                            ("untyped", "untyped"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("conteudo", mdeditor.fields.MDTextField()),
                ("paradigmas", models.ManyToManyField(blank=True, to="core.paradigma")),
            ],
        ),
    ]
