# Generated by Django 5.0.2 on 2026-05-17 19:53

import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaga",
            name="cidade",
            field=models.CharField(blank=True, max_length=100, verbose_name="Cidade"),
        ),
        migrations.AddField(
            model_name="vaga",
            name="codigo",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Código da Vaga"
            ),
        ),
        migrations.AddField(
            model_name="vaga",
            name="modelo_trabalho",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Remoto", "Remoto"),
                    ("Hibrido", "Híbrido"),
                    ("Presencial", "Presencial"),
                ],
                max_length=20,
                verbose_name="Modelo de Trabalho",
            ),
        ),
        migrations.AddField(
            model_name="vaga",
            name="nivel",
            field=models.CharField(
                choices=[
                    ("Estagio", "Estágio"),
                    ("Junior", "Júnior"),
                    ("Pleno", "Pleno"),
                    ("Senior", "Sênior"),
                    ("Staff", "Staff"),
                    ("Lider", "Líder"),
                ],
                default="Junior",
                max_length=20,
                verbose_name="Nível",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="aplicacao",
            name="anotacoes_pos_entrevista",
            field=mdeditor.fields.MDTextField(blank=True, help_text="Anotações"),
        ),
        migrations.AlterField(
            model_name="aplicacao",
            name="feedback_recebido",
            field=mdeditor.fields.MDTextField(blank=True, help_text="Feedback"),
        ),
        migrations.AlterField(
            model_name="vaga",
            name="anotacoes_pessoais",
            field=mdeditor.fields.MDTextField(help_text="Anotações"),
        ),
        migrations.AlterField(
            model_name="vaga",
            name="descricao_vaga",
            field=mdeditor.fields.MDTextField(
                help_text="Cole aqui a descrição completa da vaga:"
            ),
        ),
    ]
