# Generated by Django 5.0.2 on 2026-03-01 07:17

import django.db.models.deletion
import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="linguagem",
            options={"verbose_name_plural": "Linguagens"},
        ),
        migrations.CreateModel(
            name="Biblioteca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("aliases", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField()),
                (
                    "documentacao",
                    models.URLField(
                        blank=True,
                        help_text="Link para a documentação oficial",
                        max_length=500,
                    ),
                ),
                (
                    "link_oficial",
                    models.URLField(
                        blank=True,
                        help_text="Link para o site ou repositório",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("content", mdeditor.fields.MDTextField()),
                (
                    "linguagem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bibliotecas",
                        to="core.linguagem",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Bibliotecas",
            },
        ),
    ]
