# Generated by Django 5.0.2 on 2026-05-17 21:12

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_vaga_cidade_vaga_codigo_vaga_modelo_trabalho_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vaga",
            name="anotacoes_pessoais",
            field=mdeditor.fields.MDTextField(verbose_name="Anotações Pessoais"),
        ),
        migrations.AlterField(
            model_name="vaga",
            name="descricao_vaga",
            field=mdeditor.fields.MDTextField(verbose_name="Descrição da Vaga"),
        ),
    ]
