# Generated by Django 5.0.2 on 2026-03-01 07:42

import django.db.models.deletion
import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_linguagem_options_biblioteca"),
    ]

    operations = [
        migrations.CreateModel(
            name="Framework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("aliases", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField()),
                ("documentacao", models.URLField(blank=True, max_length=500)),
                ("link_oficial", models.URLField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("content", mdeditor.fields.MDTextField()),
                (
                    "linguagem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frameworks",
                        to="core.linguagem",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Frameworks",
            },
        ),
    ]
