# Generated by Django 5.0.2 on 2026-03-23 23:47

import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_framework"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vaga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("empresa", models.CharField(max_length=100)),
                ("link_anuncio", models.URLField(max_length=500)),
                ("data_postagem", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Interesse", "Apenas Interesse"),
                            ("Aplicado", "Currículo Enviado"),
                            ("Entrevista", "Em Fase de Entrevistas"),
                            ("Teste", "Teste Técnico em Andamento"),
                            ("Negado", "Não Selecionada"),
                            ("Aprovado", "Contratada! 🎉"),
                        ],
                        default="Interesse",
                        max_length=20,
                    ),
                ),
                (
                    "descricao_vaga",
                    mdeditor.fields.MDTextField(
                        help_text="Cole aqui a descrição completa para consulta posterior"
                    ),
                ),
                (
                    "anotacoes_pessoais",
                    mdeditor.fields.MDTextField(
                        help_text="O que você estudou ou preparou para essa vaga específica?"
                    ),
                ),
                (
                    "requisitos_bibliotecas",
                    models.ManyToManyField(blank=True, to="core.biblioteca"),
                ),
                (
                    "requisitos_frameworks",
                    models.ManyToManyField(blank=True, to="core.framework"),
                ),
                (
                    "requisitos_linguagens",
                    models.ManyToManyField(blank=True, to="core.linguagem"),
                ),
            ],
            options={
                "verbose_name_plural": "Vagas",
            },
        ),
    ]
