# Generated by Django 5.0.2 on 2026-03-23 23:54

import django.db.models.deletion
import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_vaga"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aplicacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_envio", models.DateField(auto_now_add=True)),
                (
                    "etapa_atual",
                    models.CharField(
                        choices=[
                            ("CV", "Envio de Currículo"),
                            ("Fit", "Fit Cultural / RH"),
                            ("Tecnico", "Teste Técnico"),
                            ("Gestor", "Entrevista com Gestor"),
                            ("Proposta", "Proposta Recebida"),
                        ],
                        default="CV",
                        max_length=20,
                    ),
                ),
                (
                    "curriculo_versao",
                    models.CharField(
                        blank=True,
                        help_text="Ex: CV_DataScience_v2.pdf",
                        max_length=100,
                    ),
                ),
                (
                    "portfolio_link",
                    models.URLField(
                        blank=True, help_text="Link para o projeto enviado"
                    ),
                ),
                (
                    "feedback_recebido",
                    mdeditor.fields.MDTextField(
                        blank=True, help_text="O que a empresa disse sobre você?"
                    ),
                ),
                (
                    "anotacoes_pos_entrevista",
                    mdeditor.fields.MDTextField(
                        blank=True, help_text="O que você achou da empresa?"
                    ),
                ),
                (
                    "vaga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aplicacoes",
                        to="core.vaga",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Aplicações",
            },
        ),
    ]
