# Generated by Django 5.0.2 on 2026-04-02 23:37

import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_aplicacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="BancoDeDados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("SQL", "Relacional (SQL)"),
                            ("NoSQL", "Não-Relacional (NoSQL)"),
                            ("NewSQL", "NewSQL"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("documentacao", models.URLField(blank=True)),
                ("content", mdeditor.fields.MDTextField()),
                (
                    "linguagens_compativeis",
                    models.ManyToManyField(blank=True, to="core.linguagem"),
                ),
            ],
            options={
                "verbose_name": "Banco de Dados",
                "verbose_name_plural": "Bancos de Dados",
            },
        ),
        migrations.AddField(
            model_name="vaga",
            name="requisitos_bancos",
            field=models.ManyToManyField(blank=True, to="core.bancodedados"),
        ),
    ]
